In this notebook we are going to cover some of the most fundamentals concept of tensors using Tensorflow

Introduction to Tensors

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.0


In [3]:
#create tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check number of dimensions of tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#check dimensions of vector
vector.ndim

1

In [7]:
#create a matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],[7,10]])

In [8]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
#create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,2.]], dtype=tf.float16)

In [11]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  2.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])

In [14]:
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [15]:
tensor.ndim

3

what we've created so far :

* Scaler : a single number
* vector : a number  with direction (e.g wind speed and direction)
* matrix : a 2 dimensional array of nmbers
* Tensor :an n-dimensional array of numbers (when n can be any number,a 0 dimensional tensor is a scaler ,a 1 dimensional tensor is a vector)


### Creating tensors with tf.variable

In [16]:
#create the same tensor with tf.variable() as above

changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
#lets try change one of the element in our changeble tensor
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [19]:
#How about we try .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [20]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [22]:
#create 2 random (but the same) tensors
random_1=tf.random.Generator.from_seed(42)  #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [25]:
#shuffle a tensor (valuable when you want to shuffle your data so the inherent order doesnt affect learning

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

not_shuffled.ndim

2

In [26]:
#shuffle our non shuffle tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [27]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to create tensors

In [28]:
tf.ones([3,4],dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [29]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

In [30]:
#You can also turn numpy arrays into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [31]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [32]:
B=tf.constant(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimensions
* Size

In [33]:
#create a rank 4 tensor (4 dimensions)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [35]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [36]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [37]:
rank_4_tensor.ndim

4

In [38]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

### Get Various attributes of our tensor

In [39]:
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4


In [40]:
print("Shape of tensor :",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])

Shape of tensor : (2, 3, 4, 5)
Elements along the 0 axis: 2


In [41]:
print('Element along the last axis :',rank_4_tensor.shape[-1])


Element along the last axis : 5


In [42]:
print("Total Number of elements in out tensor :",tf.size(rank_4_tensor))

Total Number of elements in out tensor : tf.Tensor(120, shape=(), dtype=int32)


# Indexing Tensors

Tensors can be index python lists

In [43]:
#Get the first 2 elements of dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [44]:
# Get the first element form each dimension from each index except for the final one

In [45]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
#create a rank 2 tesnor (2 dimensions)

rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [47]:
rank_2_tensor.ndim

2

In [55]:
#Get the  last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [56]:
# Add in extraa dimensio to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [57]:
#Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [58]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating tensors (tensors operations)

**Basic Operations**

`+`,`-`,`*`,`/`

In [59]:
# You can add values to a tensor using the addition operator

tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [60]:
tensor=tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [61]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [62]:
tensor*19

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[380, 323],
       [247, 266]], dtype=int32)>

In [63]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [64]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.7],
       [1.3, 1.4]])>

In [65]:
# We can use the tensorflow built in function to

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [66]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [23, 24]], dtype=int32)>

## **Matrix Multiplication**
* Matrix multiplication is one of the most common tensor operations in machine learning.

* There are 2 rules our tensors (or matrices) need to fulfill if we are going to matrix multiply them:

   1. The inner dimensions must match.
   2. The resulting matrix has the shape of the outer dimensions.


In [67]:
# Matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [68]:
# Matrix multiplication with python operation '@'
tensor* tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [69]:
matrix_a=tf.constant([[1,2,5],
                      [7,2,1],
                      [3,3,3]])

In [70]:
matrix_b=tf.constant([[3,5],
                      [6,7],
                      [1,8]])

In [71]:
tf.matmul(matrix_a,matrix_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [72]:
matrix_a@matrix_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [73]:
# Try to multiply 2 tensors of same shape
tf.matmul(tf.reshape(matrix_a,shape=(3,3)),tf.reshape(matrix_b,shape=(2,3)))

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,3], In[1]: [2,3] [Op:MatMul] name: 

In [78]:
x=tf.constant([[1,2],
               [3,4],
               [8,9]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [8, 9]], dtype=int32)>

In [79]:
y=tf.constant([[1,2],
              [3,5],
              [6,8]])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5],
       [6, 8]], dtype=int32)>

In [80]:
tf.matmul(x,y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [84]:
x=tf.reshape(x,shape=(2,3))

In [85]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 25,  36],
       [ 82, 120]], dtype=int32)>

In [86]:
# Can we do same with transpose
tf.transpose(x), tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 8],
        [3, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 8, 9]], dtype=int32)>)

In [88]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 25,  36],
       [ 82, 120]], dtype=int32)>

**The Dot Product**

Matrix Multiplication is also referered to as dot product

You can perform matrix multiplication using :

* `tf.matmul()`
* `tf.tensordot()`

In [89]:
#Perform the dot product on X and Y (requires X or Y transpose)

X=tf.constant([[1,2],
               [3,4],
               [5,6]])
Y=tf.constant([[7,8],
               [9,3],
               [1,6]])

In [90]:
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [95]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[39, 47],
       [56, 64]], dtype=int32)>

In [96]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[39, 47],
       [56, 64]], dtype=int32)>

In [97]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 15, 13],
       [53, 39, 27],
       [83, 63, 41]], dtype=int32)>

In [98]:
# Perform matrix multiplication between X AND Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 10, 21],
       [33, 28, 51],
       [53, 46, 81]], dtype=int32)>

In [99]:
# Check the values of Y ,reshpae Y and transpose Y

print("Normal Y:")
print(Y,"\n")


print("Y reshaped to (2,3) :")
print(tf.reshape(Y,(2,3)),"\n")


print("Y Transposed:")
print(tf.transpose(Y),"\n")

Normal Y:
tf.Tensor(
[[7 8]
 [9 3]
 [1 6]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3) :
tf.Tensor(
[[7 8 9]
 [3 1 6]], shape=(2, 3), dtype=int32) 

Y Transposed:
tf.Tensor(
[[7 9 1]
 [8 3 6]], shape=(2, 3), dtype=int32) 



In [100]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 15, 13],
       [53, 39, 27],
       [83, 63, 41]], dtype=int32)>

Generally when performing matrix multiplication on two tensors and one of the axes dosnt line up ,you will transpose (rather than reshape) to one of the tensors to get satisfy matrix multipliaction rules

### Chaning the datatype of tensor

In [102]:
# Create new tensor with default datatype (float 32)

B=tf.constant([1.8,3.4])
B.dtype

tf.float32

In [103]:
C=tf.constant([3,4])
C.dtype

tf.int32

In [104]:
#Changing float32 to float
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.8, 3.4], dtype=float16)>,
 tf.float16)

In [105]:
# Change from int32 to float 32
E=tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

# Aggrigagting tensors

Aggrigating tensors =condensing them from multiple values down to a smaller amount of values

In [106]:
#Get the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [107]:
#Get the absoulte values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation :

* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [108]:
#Create a random tensor with valeus between (0,100) and size 50
E=tf.constant(np.random.randint(0,100,size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([49, 25, 43, 83, 85, 66, 13, 50, 46, 56, 41, 91, 30, 85, 53, 17,  1,
       40, 48, 49, 52, 15, 59, 52,  9, 96, 99,  2, 30, 64, 79,  8, 76, 91,
       46, 87, 45, 62, 80, 98, 82, 40, 30, 25, 90, 86, 20, 28, 22, 48])>

In [114]:
max=tf.reduce_max(E)
max

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [115]:
min=tf.reduce_min(E)
min

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [116]:
mean=tf.reduce_mean(E)
mean

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [117]:
sum=tf.reduce_sum(E)
sum

<tf.Tensor: shape=(), dtype=int64, numpy=2592>

⚔ **Exercise:** with what we've just learned ,find then variances and standard deviation of our `E` tensor using Tensorflow methods

In [129]:
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([49, 25, 43, 83, 85, 66, 13, 50, 46, 56, 41, 91, 30, 85, 53, 17,  1,
       40, 48, 49, 52, 15, 59, 52,  9, 96, 99,  2, 30, 64, 79,  8, 76, 91,
       46, 87, 45, 62, 80, 98, 82, 40, 30, 25, 90, 86, 20, 28, 22, 48])>

In [134]:
variance=tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))
variance

<tf.Tensor: shape=(), dtype=float32, numpy=776.73444>

In [135]:
standard_deviation=tf.math.reduce_std(tf.cast(E,dtype=tf.float16))
standard_deviation

<tf.Tensor: shape=(), dtype=float16, numpy=27.86>

In [137]:
(variance)**0.5


<tf.Tensor: shape=(), dtype=float32, numpy=27.869955>

In [138]:
# finding variance of our tensor ,we need access to  tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=777>

# Finding the positional maximum and minimum

In [140]:
# create a new tensor for finding positional minimum and maximum

tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [141]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [142]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [144]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [145]:
# Check for equality

F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [146]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Sqeezing the tensor (removing all single dimensions)


In [147]:
# create a tensor to get started
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [152]:
G_squeeze=tf.squeeze(G)
G_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

## One hot encoding on tensors

In [153]:
# Create a list of indices
some_list=[0,1,2,3] # could be red ,grren ,blue ,purple

#one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [154]:
#specify custom values for one hot encoding

tf.one_hot(some_list,depth=4,on_value='yo I love deep learning',off_value='I also like to dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

### Squaring ,log ,square root

In [155]:
# Create a new tensor

H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [158]:
sqrt_root=tf.sqrt(tf.cast(H,dtype=tf.float32))
sqrt_root

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [161]:
log=tf.math.log(tf.cast(H,dtype=tf.float32))
log

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [162]:
square =tf.square(H)
square

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

### Tensors and Numpy

* Tensorflow interacts beautify with Numpy arrays

* 🥇**NOTE**:One of the main differences between a Tensorflow tensor and a Numpy array is that a TensorFlow tensor can be run on a GPU or TPU FOR (faster numerical processing )

In [163]:
# Create a tensor directly form a Numpy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [164]:
# COnvert our tensor to numpy array

np.array(J)

array([ 3.,  7., 10.])

In [165]:
type(np.array(J))

numpy.ndarray

In [166]:
# Covert tensor J to a Numpy array
J.numpy()

array([ 3.,  7., 10.])

In [167]:
type(type(J.numpy()))


type

In [169]:
# Defualts types or each are slightly differnet

numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])

# CHECK datatype of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU's

In [170]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [2]:
import tensorflow as tf

In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [14]:
!nvdia-smi

/bin/bash: line 1: nvdia-smi: command not found


> **Note** :if you have access to a cuda-enabled GPU ,Tensorflow will automaticaly use it whenever possible

In [13]:
!pip install --upgrade nvidia-pyindex

  Preparing metadata (setup.py) ... done
  Created wheel for nvidia-pyindex: filename=nvidia_pyindex-1.0.9-py3-none-any.whl size=8419 sha256=4d23f92d5826b7eec9ac9b5f659b8d34c1201ba063d58ece73920abe87f5e0a8
  Stored in directory: /root/.cache/pip/wheels/2c/af/d0/7a12f82cab69f65d51107f48bcd6179e29b9a69a90546332b3
Successfully built nvidia-pyindex
